import mongoose from "mongoose";

const drivingdetailsshcema = new mongoose.Schema({
    city_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "driving_citys"
    },
    zipcodeid:{
        type:Number,
        default:null
    },
    zip_code:{
        type:Number,
        default:0
    },
    name:{
        type:String,
    },
    type:{
        type:String,
        default:null
    },
    address:{
        type:String,
    },
    latitude:{
        type:String,
        default:null
        
    },
    longitude:{
        type:String,
        default:null 
    },
    contactNumber1:{
        type:String,
        default:null 
    },
    contactNumber2:{
        type:String,
        default:0 
    },
    open_Time:{
        type:String,
        default:null 
    },
    close_Time:{
        type:String,
        default:null 
    },
    close_Days:{
        type:String,
    },
    contact_name:{
        type:String,
    },
    website:{
        type:String,
        default:null 
    },
    email:{
        type:String,
    },
    paymentMode:[{
        type:String,
        default:null
    }],
    photo:{
        type:String,
        default:null
    },
    cover_photo:{
        type:String,
        default:null
    },
    establishedYear:{
        type:String,
    },
    services:{
        type:String,
        default:null
    },
    isfeatured:{    
        type:Number,
        default:null
    },
    rowNumber:{
        type:Number,
        default:null
    },
    schoolvalue:{
        type:Number,
        default:null
    },
    status:{
        type:Number,
        default:0
    },
    open_close:{
        type:String,
        default:null
    },
    sun:{
        type:String,
    },
    mon:{
        type:String,
    },
    tue:{
        type:String,
    },
    wed:{
        type:String,
    },
    thu:{
        type:String,
    },
    fri:{
        type:String,
    },
    sat:{
        type:String,
    },
    deleted_at:{
        type:String,
        default:null
    },
    added_by:{
        type:Number,
        default:0
    },
    deleted_by:{
        type:String,
        default:null
    }

},{timestamps:true})

const Driving_detaila = mongoose.model('driving_details', drivingdetailsshcema)
export default Driving_detaila