import mongoose from "mongoose";

const Traffic_Stateschema = new mongoose.Schema({
    state_code:{
        type:String,
        default:null
    },
    state_name :{
        type:String,
        default:null
    },
    title :{
        type:String,
        default:null
    },
    title_gu:{
        type:String,
        default:null
    },
    title_hi:{
        type:String,
        default:null
    },
    title_mr:{
        type:String,
        default:null
    },
    title_pa:{
        type:String,
        default:null
    },
    title_ta:{
        type:String,
        default:null
    },
    title_te:{
        type:String,
        default:null
    },
    title_ml:{
        type:String,
        default:null
    },
    title_kn:{
        type:String,
        default:null
    },
    title_bn:{
        type:String,
        default:null
    },
    title_or:{
        type:String,
        default:null
    },

    sub_title:{
        type:String,
        default:null
    },
    sub_title_gu:{
        type:String,
        default:null
    },
    sub_title_hi:{
        type:String,
        default:null
    },
    sub_title_mr:{
        type:String,
        default:null
    },
    sub_title_pa:{
        type:String,
        default:null
    },
    sub_title_ta:{
        type:String,
        default:null
    },
    sub_title_te:{
        type:String,
        default:null
    },
    sub_title_ml:{
        type:String,
        default:null
    },
    sub_title_kn:{
        type:String,
        default:null
    },
    sub_title_bn:{
        type:String,
        default:null
    },
    sub_title_or:{
        type:String,
        default:null
    },

    content:{
        type:String,
        default:null
    },
    content_gu:{
        type:String,
        default:null
    },
    content_hi:{
        type:String,
        default:null
    },
    content_mr:{
        type:String,
        default:null
    },
    content_pa:{
        type:String,
        default:null
    },
    content_ta:{
        type:String,
        default:null
    },
    content_te:{
        type:String,
        default:null
    },
    content_ml:{
        type:String,
        default:null
    },
    content_kn:{
        type:String,
        default:null
    },
    content_bn:{
        type:String,
        default:null
    },
    content_or:{
        type:String,
        default:null
    },

    disclaimer:{
        type:String,
        default:null
    },
    disclaimer_gu:{
        type:String,
        default:null
    },
    disclaimer_hi:{
        type:String,
        default:null
    },
    disclaimer_mr:{
        type:String,
        default:null
    },
    disclaimer_pa:{
        type:String,
        default:null
    },
    disclaimer_ta:{
        type:String,
        default:null
    },
    disclaimer_te:{
        type:String,
        default:null
    },
    disclaimer_ml:{
        type:String,
        default:null
    },
    disclaimer_kn:{
        type:String,
        default:null
    },
    disclaimer_bn:{
        type:String,
        default:null
    },
    disclaimer_or:{
        type:String,
        default:null
    },

    share_image:{
        type:String,
        default:null
    },

    share_url:{
        type:String,
        default:null
    },

    deleted_by:{
        type:String,
        default:null
    }
},{timestamps:true})

const Traffic_state = mongoose.model('Traffic_states' , Traffic_Stateschema)

export default Traffic_state